const routers = {
    home: '/',
    birthdate: '/birthdate',
    tours: '/tours',
    reviews: '/reviews',
    accordion: '/accordion',
    menu: '/menu',
    tabs: '/tabs',
    slider: '/slider',
    lorem: '/lorem',
    color: '/color-genarate',
    grocery: '/grocery-bud',
    navbar: '/navbar',
    sidebar: '/sidebar',
    stripe: '/stripe',
    card: '/card',
    cocktails: '/cocktails',
    cocktailsAbout: 'cocktails/about',
    cocktailsDetail: 'cocktails/:id',
    markdown: '/markdown',
    card_redux: '/card-redux',
    random_person: '/random-person',
};

export default routers;
